[package]
name = "graphql_lang_types"
version = "0.0.4"
edition = "2021"
license = "MIT"

[dependencies]
intern = { git = "https://github.com/facebook/relay.git#f53a93272a1d756c60de795090fe70ca9532bb67" }
common_lang_types = { path = "../common_lang_types" }
strum = { version="0.25.0", features=["derive"] }
