[package]
name = "graphql_lang_types"
version = "0.0.4"
edition = "2021"

[dependencies]
intern = { git = "https://github.com/facebook/relay.git" }
common_lang_types = { path = "../common_lang_types" }
