[package]
name = "isograph_lang_parser"
version = "0.0.1"
edition = "2021"

[dependencies]
common_lang_types = { path = "../common_lang_types" }
isograph_lang_types = { path = "../isograph_lang_types" }
logos = "0.12"
thiserror = "1.0.40"
intern = { git = "https://github.com/facebook/relay.git" }
graphql_lang_types = { path = "../graphql_lang_types" }
