[package]
name = "isograph_lang_types"
version = "0.0.4"
edition = "2021"

[dependencies]
common_lang_types = { path = "../common_lang_types" }
graphql_lang_types = { path = "../graphql_lang_types" }
intern = { git = "https://github.com/facebook/relay.git" }
u32_newtypes = { path = "../u32_newtypes" }
