name: CI

on: [push, pull_request]

jobs:
  build-compiler:
    name: Build compiler
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.72.0
          override: true
      - name: "Build Isograph with cargo"
        run: cargo build

  build-projects:
    name: Build projects
    runs-on: macos-latest
    needs: [build-compiler]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.72.0
          override: true
      - name: "Build project"
        run: cargo run --bin isograph_cli -- --config ./demos/graphql-conf-2023-demo/isograph.config.json
      - name: "Check working directory status"
        run: "./scripts/check-git-status.sh"
